# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsConfigProfiles < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.3/aws-config-profiles_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "a7adfc2661b9f26a7863cd5393adbfbc8263718b42bdbb88cc1422c0af984d57"

      def install
        bin.install "aws-config-profiles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.3/aws-config-profiles_0.1.3_Darwin_arm64.tar.gz"
      sha256 "5d0b9d5ef2640e4d7c3cbce63fcb83b143159f4cc857d1c7465c5796674146d1"

      def install
        bin.install "aws-config-profiles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.3/aws-config-profiles_0.1.3_Linux_x86_64.tar.gz"
        sha256 "daa7233ccf590a4f19174c92735cc56332235a049b194d5895c792a11c44841b"

        def install
          bin.install "aws-config-profiles"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.3/aws-config-profiles_0.1.3_Linux_arm64.tar.gz"
        sha256 "2a37857c811e80bf44e6d220d55cf63e2de0e378a7944ee8047ae65327353640"

        def install
          bin.install "aws-config-profiles"
        end
      end
    end
  end
end
