# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsConfigProfiles < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.1/aws-config-profiles_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "9b637b7819d2839306197e2c4fdf2e6e75c09c76448926b7b8e8bfb8304e1338"

      def install
        bin.install "aws-config-profiles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.1/aws-config-profiles_0.1.1_Darwin_arm64.tar.gz"
      sha256 "af09c204d0f79ffcdeb034c8fde5fcca69f94fd79acaa7fac2c7b2e8d96feb25"

      def install
        bin.install "aws-config-profiles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.1/aws-config-profiles_0.1.1_Linux_x86_64.tar.gz"
        sha256 "fade70992224bae12a073191effbe894de4b39e6c2b52865b2136fca8f8b65fb"

        def install
          bin.install "aws-config-profiles"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/aws-config-profiles/releases/download/v0.1.1/aws-config-profiles_0.1.1_Linux_arm64.tar.gz"
        sha256 "03be2af8162f08ab0c471dffaa363f29f5cc9e23a3b9d7c7570966c21edd0c67"

        def install
          bin.install "aws-config-profiles"
        end
      end
    end
  end
end
