# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsExecPf < Formula
  desc ""
  homepage ""
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v0.2.2/ecs-exec-pf_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "26c01274faf686acc008af61b2c0247f16be8bf5b9b17e0387961c8a075a0bd8"

      def install
        bin.install "ecs-exec-pf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v0.2.2/ecs-exec-pf_0.2.2_Darwin_arm64.tar.gz"
      sha256 "1af36a18e1dfcc0b94e6fa819683073e72aab6225b44fa59d5d728a4136e6e0c"

      def install
        bin.install "ecs-exec-pf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v0.2.2/ecs-exec-pf_0.2.2_Linux_x86_64.tar.gz"
      sha256 "f12dee1401287321d73bf20ff4bc6f3d7069e0197fc7dff6fbb7b328a1d5f368"
      def install
        bin.install "ecs-exec-pf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v0.2.2/ecs-exec-pf_0.2.2_Linux_arm64.tar.gz"
      sha256 "a2ede4f1d51a47c2bc7ade8b56635a39de06a21367ae0d1ad9cbf38266fa875f"
      def install
        bin.install "ecs-exec-pf"
      end
    end
  end
end
