# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsExecPf < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v1.0.0/ecs-exec-pf_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "1a21d855a9206eb7979732b838d51177792f86e358dafff596cbb10ca6529a89"

      def install
        bin.install "ecs-exec-pf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v1.0.0/ecs-exec-pf_1.0.0_Darwin_arm64.tar.gz"
      sha256 "3b6b8b5240c5120c05c06b4ea426609a2a0a40a24af55b05fc6ec33168d5134c"

      def install
        bin.install "ecs-exec-pf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v1.0.0/ecs-exec-pf_1.0.0_Linux_x86_64.tar.gz"
      sha256 "8a9ad758e069d44095e6a33a6c555dc87b860f9eae6bc8a69727dfc95b9b3b5e"
      def install
        bin.install "ecs-exec-pf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/ecs-exec-pf/releases/download/v1.0.0/ecs-exec-pf_1.0.0_Linux_arm64.tar.gz"
      sha256 "aa2b80e89638a566b22f67a96f4c5041ed8caa4240b2a0227ad9cc64ed56545e"
      def install
        bin.install "ecs-exec-pf"
      end
    end
  end
end
