# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epoch < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/epoch/releases/download/v0.1.1/epoch_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "0e432948339cda2fd57646ef7f3c049810698f600270f9eeb382b46f7315f28e"

      def install
        bin.install "epoch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/epoch/releases/download/v0.1.1/epoch_0.1.1_Darwin_arm64.tar.gz"
      sha256 "67293cfdeb28306e991dfe7abf5e42dcc4ce21406e0d3c1cf59032822ee008ec"

      def install
        bin.install "epoch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/epoch/releases/download/v0.1.1/epoch_0.1.1_Linux_x86_64.tar.gz"
        sha256 "7b6bb40fdec4743bad17925efba5999b83f6cf034588d5388cdc492637699eac"

        def install
          bin.install "epoch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/epoch/releases/download/v0.1.1/epoch_0.1.1_Linux_arm64.tar.gz"
        sha256 "b4cfd53f2b03861626297ccc68e7c9d023f75d9b975238c7846235dccafc3499"

        def install
          bin.install "epoch"
        end
      end
    end
  end
end
