# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetLocalLambda < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/get-local-lambda/releases/download/v0.0.2/get-local-lambda_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "59112fccc7a659901f810c6dfd876540ea89d9d40ae3d1bfdbee5486e7a07b0d"

      def install
        bin.install "get-local-lambda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/get-local-lambda/releases/download/v0.0.2/get-local-lambda_0.0.2_Darwin_arm64.tar.gz"
      sha256 "736e53eb584cc7f189ab8b48daf7cbca0d9e3eefd9b3259836ec7864bd93db63"

      def install
        bin.install "get-local-lambda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/get-local-lambda/releases/download/v0.0.2/get-local-lambda_0.0.2_Linux_x86_64.tar.gz"
        sha256 "ecb86ccb4689d11871ed87e63d57de2d8172251cc480999040562c1f9153213c"

        def install
          bin.install "get-local-lambda"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/get-local-lambda/releases/download/v0.0.2/get-local-lambda_0.0.2_Linux_arm64.tar.gz"
        sha256 "739f69c7b81a5c17de0ce3a161154a916dc45455e56b08d686645cd7617007d9"

        def install
          bin.install "get-local-lambda"
        end
      end
    end
  end
end
