# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohexwordlist < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.3/gohexwordlist_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "a4c2e589252daf78073c826392625a10d3699143e3d098d43953a3440c93325b"

      def install
        bin.install "gohexwordlist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.3/gohexwordlist_0.0.3_Darwin_arm64.tar.gz"
      sha256 "bf572ebe78436e8473d79964aa112e61e6998d2c422695cb758a78416d761cd9"

      def install
        bin.install "gohexwordlist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.3/gohexwordlist_0.0.3_Linux_x86_64.tar.gz"
        sha256 "cbb9a5c13acae87a99461a77bc2c932b169ddcacf751b966de749ab48d2554f1"

        def install
          bin.install "gohexwordlist"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.3/gohexwordlist_0.0.3_Linux_arm64.tar.gz"
        sha256 "03c324c9b2562be792bf0e7ecb6935fe58b4a05125c7698a8ff24d3c76f611ad"

        def install
          bin.install "gohexwordlist"
        end
      end
    end
  end
end
