# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohexwordlist < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.1/gohexwordlist_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "55b1eca40fae8d8383f3028eaaf277d28513f1148c66ab4e5634a9a93539dbd9"

      def install
        bin.install "gohexwordlist"
      end
    end
    on_arm do
      url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.1/gohexwordlist_0.0.1_Darwin_arm64.tar.gz"
      sha256 "987ca4f213fe54b213e1c227d395512f07505faeb1a368aecdd2b44812e8b5b7"

      def install
        bin.install "gohexwordlist"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.1/gohexwordlist_0.0.1_Linux_x86_64.tar.gz"
        sha256 "683b632e7201c68e5f03e7b2cdb34836e4ad9c64accffcd682d54b4940f64715"

        def install
          bin.install "gohexwordlist"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gohexwordlist/releases/download/v0.0.1/gohexwordlist_0.0.1_Linux_arm64.tar.gz"
        sha256 "da2b65130a6c19d61a3e6d405c622cfaeea2e89bd42c26a6985c17f100f10a9e"

        def install
          bin.install "gohexwordlist"
        end
      end
    end
  end
end
