# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotracks < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/gotracks/releases/download/v0.1.1/gotracks_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "8b8f4f1fdf47906ffeae2e256576a40cae98e59d39612476f4c689f3936d2497"

      def install
        bin.install "gotracks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/gotracks/releases/download/v0.1.1/gotracks_0.1.1_Darwin_arm64.tar.gz"
      sha256 "daac5957eba42e9d0e0fc0f3c67abe33dc1fc1db0e58cd47329a6e5decd41ba1"

      def install
        bin.install "gotracks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gotracks/releases/download/v0.1.1/gotracks_0.1.1_Linux_x86_64.tar.gz"
        sha256 "8099dce28ef11151a7721bf0070af78668ede5eabca085bdf9b93f6c83f325d6"

        def install
          bin.install "gotracks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gotracks/releases/download/v0.1.1/gotracks_0.1.1_Linux_arm64.tar.gz"
        sha256 "442ee63becff53321a378c7b7fa793547b002ea22a619ae6cfaade04c21b61da"

        def install
          bin.install "gotracks"
        end
      end
    end
  end
end
