# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotracks < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/gotracks/releases/download/v0.0.4/gotracks_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "b7cbf7283675c02c4393d6ed3be4d85c6917409b16b9cc537d61730138bd1297"

      def install
        bin.install "gotracks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/gotracks/releases/download/v0.0.4/gotracks_0.0.4_Darwin_arm64.tar.gz"
      sha256 "5b05a700014ad894bce834d46bfdf14e2cf4d61198365dc2ed8a119614e4c615"

      def install
        bin.install "gotracks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gotracks/releases/download/v0.0.4/gotracks_0.0.4_Linux_x86_64.tar.gz"
        sha256 "d9be0b9639b36727d03ab2cb1ec17e23dfa4d1724cd48484a81637a2563c985a"

        def install
          bin.install "gotracks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/gotracks/releases/download/v0.0.4/gotracks_0.0.4_Linux_arm64.tar.gz"
        sha256 "607ff58c3350d0551b85f1a36877be04ba8c95b0e6c2540763c73b9250cec49b"

        def install
          bin.install "gotracks"
        end
      end
    end
  end
end
