# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OutstandingPrs < Formula
  desc ""
  homepage ""
  version "1.4.2"

  on_macos do
    url "https://github.com/cuotos/outstanding-prs/releases/download/v1.4.2/outstanding-prs_1.4.2_Darwin_x86_64.tar.gz"
    sha256 "5182e2587dde5267a93b4546d6b923900464ae701bb2b84f4281b140b7b0226f"

    def install
      bin.install "outstanding-prs"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OutstandingPrs
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/outstanding-prs/releases/download/v1.4.2/outstanding-prs_1.4.2_Linux_x86_64.tar.gz"
        sha256 "faa15e5bd330428323bd55579ca3eaca229c2b8df7498c22262f119c6de9fe4b"

        def install
          bin.install "outstanding-prs"
        end
      end
    end
  end
end
