# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StsAssumeRoleEnvVars < Formula
  desc ""
  homepage ""
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/sts-assume-role-env-vars/releases/download/v1.0.9/sts-assume-role-env-vars_1.0.9_Darwin_x86_64.tar.gz"
      sha256 "0b9171b1f30b536576fbf7b1142fc611612f96273fed04c5de3e02ccab9d40ea"

      def install
        bin.install "sts-assume-role-env-vars"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/sts-assume-role-env-vars/releases/download/v1.0.9/sts-assume-role-env-vars_1.0.9_Darwin_arm64.tar.gz"
      sha256 "e4ee1fffb1ac595efa69fe5ed26889ab7a347638a9ddb04faf9b617d22194199"

      def install
        bin.install "sts-assume-role-env-vars"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/sts-assume-role-env-vars/releases/download/v1.0.9/sts-assume-role-env-vars_1.0.9_Linux_x86_64.tar.gz"
        sha256 "bc24545e8b850fd378614d531e080a11616cf22e65cc2e6529ceed8dd92ace8c"

        def install
          bin.install "sts-assume-role-env-vars"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/sts-assume-role-env-vars/releases/download/v1.0.9/sts-assume-role-env-vars_1.0.9_Linux_arm64.tar.gz"
        sha256 "342413be88a211285d12442b6327fd99449b893976d8cf19b5e89775dccd319f"

        def install
          bin.install "sts-assume-role-env-vars"
        end
      end
    end
  end
end
