# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcopen < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.0.1/tfcopen_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "ac5b4cb7b03c856b8942cda9c7f0b9979a02f84b062cb3e1b8284a7287ea06e2"

      def install
        bin.install "tfcopen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.0.1/tfcopen_0.0.1_Darwin_arm64.tar.gz"
      sha256 "f3ad347ef5a21e7aca60ff77e945569fedd5fd61bb611ea768b9a85bf2b06451"

      def install
        bin.install "tfcopen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/tfcopen/releases/download/v0.0.1/tfcopen_0.0.1_Linux_x86_64.tar.gz"
        sha256 "8b8ab21002101b3979bcd173d324d529b8f1293581c8b48d15eb0038991583c6"

        def install
          bin.install "tfcopen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cuotos/tfcopen/releases/download/v0.0.1/tfcopen_0.0.1_Linux_arm64.tar.gz"
        sha256 "c87d08786dadbe41c170b4a0546e59defd64517c5a9a4f098a89e5aa2464019b"

        def install
          bin.install "tfcopen"
        end
      end
    end
  end
end
