# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcopen < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.1.0/tfcopen_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "8bcb0575dd13889291a5a8d961d1d8ed76cd38d537a5996db8686b59f293d772"

      def install
        bin.install "tfcopen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.1.0/tfcopen_0.1.0_Darwin_arm64.tar.gz"
      sha256 "dd4bef10d0e00009d52c4de579334bb996518696bdcfac1dd2f90e3c072aed06"

      def install
        bin.install "tfcopen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.1.0/tfcopen_0.1.0_Linux_x86_64.tar.gz"
      sha256 "69beac1fdf79732ecb4c915f7f6a62e13003ae490b0e7fa420510f077c848cb8"
      def install
        bin.install "tfcopen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cuotos/tfcopen/releases/download/v0.1.0/tfcopen_0.1.0_Linux_arm64.tar.gz"
      sha256 "df20e43bd724176f59684da322256fea187c99275c44eb88ba5813a9623444c2"
      def install
        bin.install "tfcopen"
      end
    end
  end
end
